version: "3.8"
services:
  edge-server:
    build: edge-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8088/eureka
    external_links:
      - service-registry
    ports:
      - "8090:8090"
  service-registry:
    build: service-registry
    expose:
      - "8088"
    networks:
      default:
        aliases:
            - service-registry
  category-core-service:
    build: category-core-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://service-registry:8088/eureka
    links:
      - service-registry
    ports:
      - "8761:8761"
    depends_on:
      - edge-server
      - service-registry
  product-core-service:
    build: product-core-service
    links:
      - service-registry
    ports:
      - "8091:8091"
    depends_on:
      - edge-server
      - service-registry
  user-core-service:
    build: user-core-service
    links:
      - service-registry
    ports:
      - "8759:8759"
    depends_on:
      - edge-server
      - service-registry
  role-core-service:
    build: role-core-service
    links:
      - service-registry
    ports:
      - "8760:8760"
    depends_on:
      - edge-server
      - service-registry
  product-composite-service:
    build: product-composite-service
    links:
      - service-registry
    ports:
      - "8763:8763"
    depends_on:
      - edge-server
      - service-registry
      - product-core-service
      - category-core-service
  hystrix-dashboard:
    build: hystrix-dashboard
    links:
      - service-registry
    ports:
    - "8097:8097"
    depends_on:
      - product-composite-service
      - product-core-service
      - category-core-service
      - login-system-composite-service
      - role-core-service
      - user-core-service

  login-system-composite-service:
    build: login-system-composite-service
    links:
      - service-registry
    ports:
      - "8762:8762"
    depends_on:
      - edge-server
      - service-registry
      - role-core-service
      - user-core-service
