GET http://localhost:8763/product/find?description=test
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im50UHowYzhmWVJqNHN0QWlqdTlqODl6UWJKbjAwZU9wSm5nNGdNQ0NpSkE9In0.eyJhdWQiOlsidXNlci1jb3JlLXNlcnZpY2UiLCJwcm9kdWN0LWNvbXBvc2l0ZS1zZXJ2aWNlIiwicm9sZS1jb3JlLXNlcnZpY2UiLCJjYXRlZ29yeS1jb3JlLXNlcnZpY2UiLCJwcm9kdWN0LWNvcmUtc2VydmljZSJdLCJzY29wZSI6WyJwcm9kdWN0LWNvbXBvc2l0ZS1zZXJ2aWNlIiwicHJvZHVjdC5yZWFkIiwicHJvZHVjdC53cml0ZSIsInJvbGUucmVhZCIsInJvbGUud3JpdGUiLCJ1c2VyLnJlYWQiLCJ1c2VyLndyaXRlIiwiY2F0ZWdvcnkucmVhZCIsImNhdGVnb3J5LndyaXRlIl0sImV4cCI6MTYxMDk0NzAxNSwianRpIjoiN2Q3NmIxM2UtZmU4OC00Y2Y5LWJjMTYtYzU1YjU3ZWY5OGY4IiwiY2xpZW50X2lkIjoiY29yZS1zZXJ2aWNlLWNsaWVudCJ9.N7ld1X0c2cx9XCLnh4HRFvGXHDtV1oBVU8IyFk9VYRHtZQ3DZ6osmAGaFfsgK4NIGzQXD9vmuQB9ieDIg_COl6BIbWPG85h6pj-DvSPU9LqF8g0_I_X_3QJF7H0ziF4dFhFx8pCPMm3tMUwJQK9IJHMf1t3n1M_jojW91OSiriZ7U1C9lwHCeEBABXek0W3v96cutdlY3NA2Z5NIkakGGT00GBIYkA21P6gk_46BodfHJPrDf-aKhYP29swfNRP5WPDSEenQDo1rTTDVdhCXDSTwf7DPM-ZZr-vYs-RHzbucJlN3emAvgWNpXS1zyLbONc__UVBuHbmukwfyp_-vsQ
