GET http://localhost:8763/product/find?description=test
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlF0NzBzVHYyZGcwQVhUcmQzdGNlcCtFQ1VZSkp6b05pRGpvUXJwWVFXZUE9In0.eyJhdWQiOlsidXNlci1jb3JlLXNlcnZpY2UiLCJwcm9kdWN0LWNvbXBvc2l0ZS1zZXJ2aWNlIiwicm9sZS1jb3JlLXNlcnZpY2UiLCJjYXRlZ29yeS1jb3JlLXNlcnZpY2UiLCJwcm9kdWN0LWNvcmUtc2VydmljZSJdLCJzY29wZSI6WyJwcm9kdWN0LWNvbXBvc2l0ZS1zZXJ2aWNlIiwicHJvZHVjdC5yZWFkIiwicHJvZHVjdC53cml0ZSIsInJvbGUucmVhZCIsInJvbGUud3JpdGUiLCJ1c2VyLnJlYWQiLCJ1c2VyLndyaXRlIiwiY2F0ZWdvcnkucmVhZCIsImNhdGVnb3J5LndyaXRlIl0sImV4cCI6MTYxMDk0MDMxNywianRpIjoiNGFhMTgyNmEtN2MxYi00ODUyLWIwZGMtZDc3YzQ2MzY4OTYxIiwiY2xpZW50X2lkIjoiY29yZS1zZXJ2aWNlLWNsaWVudCJ9.J-Ojw4DI9H-hR5hulreh1jKDJ2eE1eWxZJRfz8eX5oWXzqTT733fpb40DkGhYT5kEzvQg7FU0ZWYQMOAtP3bAekDP445XHJFBTrVSF2_oPkSsAKdUu4y_cniuHd-69OVVxnWOL95D7tPQcv173z6JmKX8jAMK9pL5itWWkVQCcDlMidtQD1LXPs-u368cWx4t3gUqgfi4xYcFp3yJpd1MH1eM4uLofKd_5te4bIfN1WNcqEQcKGEGAURHpiq21IEF93DiJZ3pn5kES9pTzrK1NGxAov_QiEaybavAkZ5qEgRV03reyUf4STS7WggX_URBiJa8MrrWY5pOH1fIjOMQg
