spring:
  application:
    name: Edge Server (Zuul) | Loadbalancer (Ribbon)
server:
  port: 8089
eureka:
  client:
    healthcheck:
      enabled: true
  # Da dies das Register selbst ist wird sich weder registriert, noch die Service Registry abgerufen
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8088/eureka


debug: false
zuul:
  servlet-path: /api
  routes:
    appservice:
      path: /appservice/*
      serviceId: application-service
