spring:
  application:
    name: Edge Server (Zuul) | Loadbalancer (Ribbon)

server:
  port: 8090
eureka:
  client:
    healthcheck:
      enabled: true
  # Da dies das Register selbst ist wird sich weder registriert, noch die Service Registry abgerufen
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8088/eureka}

logging:
  level:
    root: WARN
    org.springframework: INFO

security:
  oauth2:
    client:
      messaging-client-client-creds:
        client-id: core-service-client
        client-secret: secret
        grant-type: client_credentials
        access-token-uri: http://localhost:8888/oauth/token
        scope: product.read, product.write, role.read, role.write, user.read, user.write, category.read, category.write

debug: false
zuul:
  ignoredServices: '*'
  routes:
    login:
      path: /login
      serviceId: login-system-service
    logout:
      path: /logout
      serviceId: login-system-service
    user/register:
      path: /user/register
      serviceId: login-system-service
    product/add:
      path: /product/add
      serviceId: product-composite-service
    product/find:
      path: /product/find
      serviceId: product-composite-service
    product:
      path: /product
      serviceId: product-service
    product-level-2:
      path: /product/*
      serviceId: product-service
      stripPrefix: false
    category:
      path: /category
      serviceId: category-service
