GET http://localhost:8091/product
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRkTS9aTHdDNkNHc3ZOdGJzbXd1RzJFM2plbHpIUmNGVk4vbDdidW5teTA9In0.eyJhdWQiOlsidXNlci1jb3JlLXNlcnZpY2UiLCJyb2xlLWNvcmUtc2VydmljZSIsImNhdGVnb3J5LWNvcmUtc2VydmljZSIsInByb2R1Y3QtY29yZS1zZXJ2aWNlIl0sInNjb3BlIjpbInByb2R1Y3QucmVhZCIsInByb2R1Y3Qud3JpdGUiLCJyb2xlLnJlYWQiLCJyb2xlLndyaXRlIiwidXNlci5yZWFkIiwidXNlci53cml0ZSIsImNhdGVnb3J5LnJlYWQiLCJjYXRlZ29yeS53cml0ZSJdLCJleHAiOjE2MTA4NzkxOTEsImp0aSI6ImFiYzA3NzJkLTBlNmUtNGQwNy1iNDlhLWM5Mzk4OWYxNGVhNCIsImNsaWVudF9pZCI6ImNvcmUtc2VydmljZS1jbGllbnQifQ.j5-PRSM_qdL5A0727DRfkBWNMtSmx6YOn81T7-nr5QSjTayzaoQtgm2AmDmmezxAP5X_PYAgY38weBz8LFTFK4Ub-fSahdyjiC03uSU1FPv8goJhWq_NsVcC4nnYnMr9hJ4nYhvaAQyaVaXUBi1cdSdNJZokvDGuEKBtTQhSgFE3PDqviD3mcnKqiw5zo3ZdjmMJqHmudLeQMRqNStXVLE4_Xst0o8WbpumfmBeXOllr2TwTkcocrgmUAtH5wJvxCyBBo6D-Rooo0NDFZDIcdjZy3z-UumANn2FSKjpP4QCvagBmwXbwayQC3-6COYlQP5awjjuf_fgFmojmkzscKg
