GET http://localhost:8091/product/find?description=test
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBHRFRoSWZEem1DTFR4OHNsd3ZVREFOUEpMUHQwWXFFQXRkL1ZGQ2NmVlk9In0.eyJhdWQiOlsidXNlci1jb3JlLXNlcnZpY2UiLCJyb2xlLWNvcmUtc2VydmljZSIsImNhdGVnb3J5LWNvcmUtc2VydmljZSIsInByb2R1Y3QtY29yZS1zZXJ2aWNlIl0sInNjb3BlIjpbInByb2R1Y3QucmVhZCIsInByb2R1Y3Qud3JpdGUiLCJyb2xlLnJlYWQiLCJyb2xlLndyaXRlIiwidXNlci5yZWFkIiwidXNlci53cml0ZSIsImNhdGVnb3J5LnJlYWQiLCJjYXRlZ29yeS53cml0ZSJdLCJleHAiOjE2MTA5MzgzODQsImp0aSI6ImY4ZWQ1Y2Y1LTVjOGMtNDU4My04ZmIwLWU5ZWQ4M2ZmMzE4MiIsImNsaWVudF9pZCI6ImNvcmUtc2VydmljZS1jbGllbnQifQ.Zup47QjeSnj2qWIY3HYzBbrV2FODIFotuVcHDuCToZMOTc6fFBgr6t-KCL6UkkoieGlGfcUa4XwK1jy-BL6zl85mpJfY7iEySYzueRFovL-wJz_cu-feylBYJ1yLnR36UjSsSpyx-cws0LZJxkp-iIJiitV7D-M8mKyxcBG612sz3B3AG1UPBrQDfwJFYc8ZAw3BoNzD6C6R8vNmqlhOPw5wZzzA_5YcaYESTuZnG9WVXsn8HsYQmKLDt1yWX7t3aIq_sib4gUXSBmGOezFk0x_Y6hdZTEcwPBEOlbhRIHcD0yhQY1O9Ym-LWqy-3FawXdtxh181bFBQ8-ICZAcujg
